modmap:
  - name: Except Chrome
    application:
      not: Google-chrome
    remap:
      CapsLock: Esc
keymap:
  - name: Emacs binding
    remap:
      C-b: left
      C-f: right
      C-p: up
      C-n: down
