virtual_modifiers:
  # CapsLock を修飾キーとして扱う
  - CapsLock

modmap:
  - name: Switch IME with Alt
    remap:
      Alt_L:
        held: Alt_L
        alone: Muhenkan
        alone_timeout_millis: 150
      Alt_R:
        held: Alt_R
        alone: Henkan
        alone_timeout_millis: 150

keymap:
  - name: Function keys
    remap:
      CapsLock-1: F1
      CapsLock-2: F2
      CapsLock-3: F3
      CapsLock-4: F4
      CapsLock-5: F5
      CapsLock-6: F6
      CapsLock-7: F7
      CapsLock-8: F8
      CapsLock-9: F9
      CapsLock-0: F10
      CapsLock-Minus: F11
      CapsLock-Equal: F12

  - name: Convert
    remap:
      CapsLock-i: F7

  - name: for 60% Layout
    remap:
      CapsLock-Apostrophe: Grave
      # CapsLock-Backslash: Print
      CapsLock-Backspace: Delete
      # Alt-Backspace: Delete

  - name: Shortcuts
    remap:
      Alt-q: Alt-F4
      CapsLock-t: Ctrl-t
      CapsLock-r: Ctrl-r
      CapsLock-c: Alt-c
      CapsLock-Space: Super-a

  - name: Emacs keybindings
    remap:
      # Cursor
      CapsLock-b: Left
      CapsLock-f: Right
      CapsLock-p: Up
      CapsLock-n: Down
      # Beginning/End of line
      CapsLock-a: Home
      CapsLock-e: End
      # Page Up/Down
      CapsLock-u: PageUp
      CapsLock-v: PageDown
      # Newline
      CapsLock-m: Enter
      CapsLock-j: Enter
      CapsLock-o: [End, Enter, Home, Left]
      # Delete
      CapsLock-d: Delete
      CapsLock-h: Backspace
      # Kill line
      CapsLock-k: [Shift-End, C-x]
