# Reference: [dotfilesのすゝめ | kouki’s blog](https://blog.kmdkuk.com/2022/07/16/dotfilesのすゝめ.html)
name: CI

on:
  push:

jobs:
  run-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dotfiles on Ubuntu
        run: bash setup/linux/setup.sh
