# Reference:
# - [dotfilesのすゝめ | kouki’s blog](https://blog.kmdkuk.com/2022/07/16/dotfilesのすゝめ.html)
# - [Running jobs in a container - GitHub Docs](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container)
# - [GitHub Actionsを使って、自分用にカスタムしたArch LinuxのISOイメージを作る](https://zenn.dev/inkohx/articles/3dbe67c0db1322)
name: CI

on:
  push:

jobs:
  setup-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotfiles on Ubuntu
        run: bash setup/linux/setup.sh

  setup-archlinux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
    steps:
      - name: Install sudo
        run: |
          pacman-key --init
          pacman-key --populate
          pacman -Syy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm sudo
      - uses: actions/checkout@v4
      - name: Setup dotfiles on Arch Linux
        env:
            USER: root
        run: |
          su ci
          bash setup/linux/setup.sh
